apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: common
  name: common
  namespace: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: common
    spec:
      containers:
      - image: kube-01.bd.com:5000/fitness/common:0.1
        name: common
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: common
    release: fitness
  name: common
  namespace: fitness
spec:
  ports:
  - name: http-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: common
  type: NodePort
status:
  loadBalancer: {}
